from openai import OpenAI
import os
from dotenv import load_dotenv

load_dotenv()

class CritiqueAgent:
    def __init__(self):
        self.client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

    def get_critique(self, features, prediction):
        sys_prompt = """
        ROLE: Music analysis agent.
        INPUTS: 
        1) Features used by ML model.
        2) Predicted popularity (1-100).
        
        EXPECTATION: Analyze features and provide a supportive argument for the predicted popularity.
        RULES:
        1) DO NOT mention feature names or values.
        2) Concise output (2-3 sentences).
        3) Act as if the output was generated by yourself.
        """
        
        user_prompt = f"Features: {features}\nPredicted Popularity: {prediction}"
        
        try:
            completion = self.client.chat.completions.create(
                model="gpt-3.5-turbo",
                messages=[
                    {"role": "system", "content": sys_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                temperature=0.1,
            )
            return completion.choices[0].message.content
        except Exception as e:
            return f"Critique generation failed: {str(e)}"
